### ISSUE TITLE
How do I install this.

### ISSUE THREAD

**Issue by JamesAnelay** [dkvashninbay/magento2plugin#1]
So this looks great!
However having never touched java not quite sure how i'm meant to install it. I assume I need to turn this into a .jar file to use in phpstorm is there a version of this allready created anywhere?
Thanks - James

**Comment by dkvashninbay** [comment]
Hi James,

To use plugin in IDE, just install it from jetbrains plugin repository - https://plugins.jetbrains.com/plugin/8024?pr= 
From IDE: settings->plugins->browse repositories-> search "Magento2"-> install and restart

**Comment by JamesAnelay** [comment]
Perfect thanks - Should have thought of that.

- James
