### ISSUE TITLE
Add smart cache invalidation

### ISSUE THREAD

**Issue by amenk** [dkvashninbay/magento2plugin#3]
Add an option to invalidate the cache, but only those of recently changed files.

i.e. when I am doing layout XML stuff, only invalidate the specific caches.

Because full cache invalidation is super slow in Magento2 ..

**Comment by dkvashninbay** [comment]
Hi,

Thanks for a feature request!
Please correct me if I am wrong, but you are asking for an application cache invalidation not phpstorm specific cache, do you?
If so, I suggest to implement (or ask Magento2 team to implement) some file watcher via Grunt on your dev machine similar to watch.js which will refresh specific caches on update in files located under */layout/ directory.
Example:
 https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/dev/tools/grunt/configs/watch.js#L14
Use case:
http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html

So in a case such grunt task exists (or will exist), there is no need to implement such in current plugin, as grunt is already integrated in PhpStorm.

**Comment by amenk** [comment]
Good point.

**Comment by dkvashninbay** [comment]
Closing as resolved.
